# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "uhci_hcd" "ehci_pci" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."luks-dde2bd36-3187-44db-b5ce-b132ddd115ab".device = "/dev/disk/by-uuid/dde2bd36-3187-44db-b5ce-b132ddd115ab";
  boot.initrd.luks.devices."luks-814a6623-b66a-412b-b90c-3e30b3c0631e".device = "/dev/disk/by-uuid/814a6623-b66a-412b-b90c-3e30b3c0631e";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a7f2cdbf-f6d2-440e-bc40-3ed1c63db6c9";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5F51-3C13";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/33dc0e6c-9614-4210-801f-2cd63d44bc60"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens33.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
